import unreal as u,json
ae=u.get_editor_subsystem(u.EditorActorSubsystem)
world=u.get_editor_subsystem(u.UnrealEditorSubsystem).get_editor_world()
surface=next(a for a in ae.get_all_level_actors() if 'SurfaceManager' in a.get_name())
surface.set_editor_property('build_in_construction_script',False)
old=list(surface.get_components_by_class(u.StaticMeshComponent))
for c in old:c.destroy_component(surface)
surface.set_editor_property('chunk_height_offset',-130.002014)
surface.call_method('RebuildSurface')
center,extent=surface.get_actor_bounds(False)
assert abs(center.z+extent.z-56.55)<1, str((center,extent))
fill=next((a for a in ae.get_all_level_actors() if a.get_actor_label()=='E02_SoftFill'),None)
if not fill:
    fill=ae.spawn_actor_from_class(u.DirectionalLight,u.Vector(0,0,1000),u.Rotator(pitch=-55,yaw=140,roll=0))
    fill.set_actor_label('E02_SoftFill');fill.tags=['STP_Expedition02'];fill.set_folder_path('Environment/Expedition02/Lighting')
fill.light_component.set_intensity(1.6)
fill.light_component.set_cast_shadows(False)
fill.light_component.set_light_color(u.LinearColor(.78,.85,1,1))
u.EditorLoadingAndSavingUtils.save_map(world,'/Game/PlanetLevel_RockPreview')
with open(r'C:\UE5\SurviveThePlanet 5.8\Saved\Expedition02\finalize.json','w') as f:json.dump({'removed_old_ground_components':len(old),'ground_bounds':str((center,extent)),'construction_rebuild':False},f,indent=2)
exec(open(r'C:\Users\qtxmj\AppData\Local\Temp\stp_ue02_review.py').read())
